# Example configuration with two servers

servers:
  # When a client connects using the survival.example.com address, we create a
  # proxy tunnel between the client and localhost:25566. This is useful when
  # the upstream server is not accessible from the internet, for example if you
  # only want to forward a single port.
  survival:
    from:
      - survival.example.com
    to: localhost:25566

  # When a client connects using the creative.example.com address, we redirect
  # the client to 1.2.3.4:25567. This is useful when the upstream server is
  # accessible from the internet, because this variant does not introduce any
  # additional latency or overhead once the connection is up.
  creative:
    from:
      - creative.example.com
    to: 1.2.3.4:25567
    redirect: true